### ISSUE TITLE
Navbar - Stackblitz broken

### ISSUE THREAD

**Issue by pslyman** [HealthCatalyst/Fabric.Cashmere#1031]
In the Stackblitz examples for both Navbars, the component does not loads completely. Icons are broken, and most buttons aren't there.

![image](https://user-images.githubusercontent.com/22920382/66960355-878cfc80-f029-11e9-9c06-945a31c7a513.png)

![image](https://user-images.githubusercontent.com/22920382/66960378-907dce00-f029-11e9-8702-7c01c077fa93.png)

**Comment by joeskeen** [comment]
There are two problems here:
1 ) the local assets are included in the StackBlitz but StackBlitz itself does not work with them (it is a known bug: https://github.com/stackblitz/core/issues/617 )
2 ) the examples with a module file don't work because the example component isn't exported from the example module.  This is also a known bug: https://github.com/HealthCatalyst/Fabric.Cashmere/issues/997

I'm going to mark this as a duplicate and close it.  Please see #997 to track this issue.  I'll also bump up the priority.
