### ISSUE TITLE
Disabled boxes showing differently

### ISSUE THREAD

**Issue by HCJammerman** [HealthCatalyst/Fabric.Cashmere#1047]
**Summary**

When I am using the Ops Console, I unchecked the "Delay Entity Processing until prerequisites are resolved" and the **disabled** boxes directly below that had different appearances.  The first one showed the NO symbol while the second one grayed out and showed the NO symbol.

![image](https://user-images.githubusercontent.com/27374237/68056559-100dcd00-fcb9-11e9-9ec5-39ef19da4c11.png)

![image](https://user-images.githubusercontent.com/27374237/68056564-169c4480-fcb9-11e9-87a2-e7ac297dc041.png)

![image](https://user-images.githubusercontent.com/27374237/68056379-983fa280-fcb8-11e9-95f4-90fbb3bb57d7.png)

**Comment by andrew-frueh** [comment]
Hey @HCJammerman & @jonest  - thanks for submitting this issue.  I'm thinking that a class must be getting overridden here.  Input boxes should gray out like your select box is.  Take a look at the "Input Prefix" example on this page:

https://cashmere.healthcatalyst.net/components/input/examples

On there you'll see an example where the inputs _should_ be grayed out (if they aren't on your browser that explains the issue).  And maybe double check there isn't anything different in the syntax of that example from what you're doing to disable the input.

Otherwise - check that div with `hc-form-field-flex` and see if the `.hc-form-field-disabled` class is being applied, or if elements of that class are being overridden.

**Comment by jonest** [comment]
I see the input boxes you mentioned on the example pages and I see them as disabled, so looks like we've got something overriding on our end. Thanks! Closing this out and logging a bug on our end.
