### ISSUE TITLE
Move the link to HealthCatalyst.com in the Help dropdown to inside the About modal

### ISSUE THREAD

**Issue by cedar-ave** [HealthCatalyst/Fabric.Cashmere#105]
Between legal, privacy, copyright, terms of use, and the HC site links, some prototypes have up to eight items in the Help dropdown. (Among those links mentioned, at this time the Cashmere site only reflects the HealthCatalyst link in the dropdown.)

Many of these links could be presented as links on the About modal to make it easier for the user to locate what might be considered the most critical user resources -- user feedback and documentation.

Ideally the standard links might be:
Browse help topics
Send us your feedback
Health Catalyst Community
What's new
Get help (or Contact us)
About (which opens the About modal that has links to Terms of use, Privacy, Legal and copyright notices, etc.)

Specifically re: the HealthCatalyst.com link, it is (mainly) marketing content not of acute interest to app users.

**Comment by benjanderson** [comment]
the help dropdown is just an example and is customizable for each application that uses it. In fact, many apps wont even have that help drop down

![image](https://user-images.githubusercontent.com/1934453/35941213-c4f75f9e-0c0e-11e8-9ef7-a6505499a247.png)

This is a great improvement to the template as many will just use it as their starter. So I would like to keep this issue until we can make the suggested links. The reason the about link doesn't open a modal is because we don't have a modal component quite yet, which is another reason to keep this issue open as we can improve the template after that component has been completed

**Comment by andrew-frueh** [comment]
@cedar-ave - I don't think they're on GitHub, otherwise I would tag them, but before we make any decisions on this we'll want to bring the Knowledge Development team into the conversation - specifically Amanda and Heather.  The help menu is kind of their domain, and I just met with them yesterday about the steps they're taking to standardize our help menus across apps.  They are planning on using a tool called [WalkMe](https://www.walkme.com/) for many of the help menus, that provides links as well as guided tutorials.  But when WalkMe isn't present, they were also coming up with a more standard list for the popover help menu Ben referenced.  So definitely reach out to Amanda or Heather if you have suggestions on those help menu standards.

**Comment by cedar-ave** [comment]
I will reach out to them and request that if it is not already in their plans, that they broaden their decision-making process to include all stakeholders. Standardization of a major element across all apps should be a collaborative effort.

**Comment by andrew-frueh** [comment]
Sounds good, I'm sure they'd welcome the additional input.  They just started thinking the standardization bit of it through yesterday, so no decisions have been made or anything like that.  So it would be perfect timing to open it up to a wider group (and legal too for their input on EULAs, etc)

**Comment by andrew-frueh** [comment]
Thanks for bringing this up @cedar-ave - helped me realize that we definitely should make an About Dialog component in Cashmere so we can standardize what and how the information in there is presented.  Created #107 and have added it to the project plan.
