### ISSUE TITLE
cashmere auto changed date for some dates

### ISSUE THREAD

**Issue by lindachan465** [HealthCatalyst/Fabric.Cashmere#1056]
**Summary**

If I type in 2/29/2019, 2/30/2019 or 2/31/2019 (not real dates), instead of getting an error, the date  field automatically moved those dates to 3/1/2019, 3/2/2019, 3/3/2019. I would expect we get an error much like if I entered 2/32/2019 to say this is not a valid date. (note this applies to anything that has day component <=31 but not valid for the month, e.g., 4/31/2019, 6/31/2019, etc)

**Reproduction**

Steps to reproduce:

1. type in 2/31/2019
2. Either tab to move to a different field or click on another field
3. You'll see the date got auto updated

**Comment by andrew-frueh** [comment]
Thanks for reporting this @lindachan465 - I can validate that I'm seeing the same behavior on the demo site.  I'll check this out on Wednesday and hopefully get a PR submitted.

**Comment by andrew-frueh** [comment]
Sadly @lindachan465 - this is actually an issue with javascript's `Date` object, not something unique to our component:

https://stackoverflow.com/questions/21188420/javascript-date-validation-not-validation-february-31

For any date entered over 31, it will throw an invalid error, but or anything under 31 that happens to not exist in that month, it automatically throws it into the next month.  As that StackOverflow article mentions, the best way to validate whether that happened is to compare the value you put in to the Date object with the value you get out.  

But the problem is that we accept every possible date format in the input ("2/31/10", "Feb 31, 2010", etc), so there isn't an easy way for me to check the before and after, short of parsing every possible date format (and there are a lot).  Because the output will always be consistent, but I won't have any way of knowing exactly what format came in.  So unless @joeskeen can think of something clever here that I'm missing, I'm afraid this might just be a javascript limitation.
