### ISSUE TITLE
Get identifier or object of selected preset from date-range

### ISSUE THREAD

**Issue by njwhc** [HealthCatalyst/Fabric.Cashmere#1095]
**Description**

It would be great if the date-range would uniquely identify which preset was used.

**What problem are you trying to solve?**

Imagine your application supplies a date-range component with user-configured presets that are dynamic with respect to today. Here is an example. A user can decide that their fiscal year starts on July 1st. They could also could add two presets of "2 Quarters to Date" and "Fiscal Year to Date". On any given day, a component outside the date range calculates the start and end dates of these presets and supplies them, with appropriate labels, to the date-range component.

![image](https://user-images.githubusercontent.com/30876456/71016235-18c43200-20b2-11ea-85fe-60a73677df25.png)

However, sometimes, these presets have the same start and end dates. Suppose it is December 17th, 2019. "2 Quarters to Date" is 7/1/2019 to 12/17/2019. Likewise, "Fiscal Year to Date" is also 7/1/2019 to 12/17/2019.

When a user clicks the Apply button, the date-range emits only the start and end dates. Components outside of the date-range component do not know which of the two presets were selected. Of course, those two presets have the same start and end dates, but presentationally, it's impossible to know which preset the user actually used within the date-range.

Notice in the following screenshot that the selected preset is shown to the user:

![image](https://user-images.githubusercontent.com/30876456/71016591-9ab45b00-20b2-11ea-98f9-06149fed4587.png)

If the "Fiscal Year to Date" preset is selected from the date-range, the external components only get  the start and end dates and don't know which preset to display:

![0D91D903-8F29-401A-86AD-4ED5402BA573](https://user-images.githubusercontent.com/30876456/71016907-10b8c200-20b3-11ea-824b-6ee06ca85d0a.GIF)

If the date-range required unique labels for the presets or allowed for a identifier to be supplied with a preset and then emitted this identifier with the selected start and end date, it would be possible to distinguish between presets that have different labels, but the same start / end dates.

**Comment by andrew-frueh** [comment]
I like the idea @njwhc - let's discuss this on Thursday when we're meeting about the other date picker issue.

**Comment by andrew-frueh** [comment]
Hey @njwhc & @jacquie - have a look at my implementation of what we discussed yesterday:

https://github.com/HealthCatalyst/Fabric.Cashmere/pull/1097

Biggest difference is that I have it emitting a DateRange if no preset is selected.  That way you should only have to subscribe to this emitter instead of `selectedDateRangeChanged` if you're interested in presets.  So it's not a breaking change for those using the other emitter, just gives another option now for people who need to know the selected preset.  But it should be a matter of choosing one or the other, not having to subscribe to both.

Look forward to your feedback!
