### ISSUE TITLE
hc-form-field without label doesn't line up to form fields with labels

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1127]
**Summary**

If an hc-form-field doesn't have  a label, then it won't line up vertically with the other hc-form-fields that include an hc-label

**Reproduction**

Stackblitz for reproduction:
https://angular-cy7wpk.stackblitz.io

**Comment by corykon** [comment]
@Techgeekster could you share the version of the url that shows the code editor, too?

**Comment by andrew-frueh** [comment]
This is a tricky one, because we removed that padding based on complaints about extra padding on inputs if they weren't using a label.  @Techgeekster - I wonder if the solution in a case like your Stackblitz is just to include an empty hc-label?  That would preserve the alignment, and wouldn't introduce unnecessary padding.  Thoughts on that @corykon?

**Comment by Techgeekster** [comment]
@andrew-frueh That's what we ended up doing.  It was a nice quick fix.
@corykon Crap, I don't have it anymore.  If we want to keep this as an issue, I can replicate it again.

**Comment by corykon** [comment]
@Techgeekster no worries! pretty easy for us to replicate. @andrew-frueh Maybe we avoid a code change, just add a note in the docs about the workaround, call this one good?

**Comment by andrew-frueh** [comment]
Agreed @corykon.  Glad the fix worked @Techgeekster :-)
