### ISSUE TITLE
Ability to style the navbar for different environments

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#1130]
**Describe your idea**

Some clients are requesting the ability to easily distinguish test, dev, and prod environments by either a different icon or a different color for the navbar. A navbar seems like the quickest, most obvious way to differentiate these environments.

**What problem are you trying to solve?**

Clients currently have to double check the URL for our apps to be sure they're in the correct environment. Changing a color would make it much more obvious to avoid doing things in the wrong environment.

**Additional context**

Another option that a consumer of this library could be to just change the icon locally. We could 
 perhaps just offer an option in Cashmere to slap some text over the icon or something like that, but if we're going to go that route, changing the color would probably be just as easy and more obvious.

We could also just override the CSS to change the color, but making it a part of Cashmere might entice consumers to differentiate more.

![image](https://user-images.githubusercontent.com/3075414/72826290-cc7e8b80-3c35-11ea-83ba-2c553df8841d.png)

![image](https://user-images.githubusercontent.com/3075414/72826356-e6b86980-3c35-11ea-850e-f05d4b856b90.png)

**Comment by andrew-frueh** [comment]
Hey @jonest - thanks for the request. We actually have a Banner component in the library for the purpose you mentioned (to differentiate environments):

https://cashmere.healthcatalyst.net/components/banner/examples

I’d hesitate to change the colors of the Navbar for that because it’s a central branding element.  That said, we do have an issue to provide skinning support of Cashmere as a whole - like if someone is using Cashmere without Catalyst branding: #999

**Comment by jonest** [comment]
Thanks for the info @andrew-frueh ! Both of those things would handle what we're looking to do :) Stay tuned for an Open Space session ;)
