### ISSUE TITLE
Improvements to using HcPop as Tooltips

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#1203]
**What problem are you trying to solve?**

Currently using HcPop as a tooltip has some disadvantages:

* Each tooltip needs its own `<hc-pop>...</hc-pop>` definition.  This is much more verbose than using the `[title]=""` attribute.  If you have many tooltips, this can quickly become the majority of your template file.
* Tooltips wired up using the `hover` trigger show immediately.  If you have tooltips on a control-dense view (such as a table), moving your mouse across the screen causes a ton of tooltips to flash in and out.
* Tooltip definitions are separated from the place they are used.  It's also unlikely that they will be reused.

**Describe your idea**

Implement one of the following improvements:

* Create a new `hcTooltip=""` directive that expects a string value, and pops up after a 500ms delay.  This could/should be based on HcPop under the hood.
* Create a new trigger for HcPop called something like `hoverDelay` for popping up on hover after a 500ms delay.  Allow HcPop to accept either an `<hc-pop>` reference or a plain string value.

**Additional context**

https://stackblitz.com/edit/angular-675wud?file=src/app/popover-tooltip/popover-tooltip-example.component.html

**Comment by andrew-frueh** [comment]
@joeskeen @corykon  I want to queue this up with you for next week.  @CristianIxcamey and I got this one started as a new component, but with the way we have it implemented, it will be making a separate `hcPop` for every tooltip (because hcPop is part of the component template).  That will probably work, but it seems like it could really bloat the DOM if someone has like 50 tooltips on a page.

So I wondering if a smarter way might be to have a tooltip service that stores a single popover tooltip.  And then we're just populating the content of that popover rather than making a zillion individual ones.
