### ISSUE TITLE
Updated Demo Site Layout

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#126]
We've had some conversations about updating the layout and navigation of our demo site, and this is what I'm proposing as an upgrade:

https://xd.adobe.com/view/7a081799-3095-46c2-b22b-3b9f6393eb1d/

It borrows from some patterns on the Angular Material site and other documentation sites I like.  Rather than separating the component demo and documentation into two separate navbar tabs, @corykon had the great suggest to include horizontal tabs on a single component section.  That way the developer info is still separate, but it keeps all the info about a single component in one place.

I also gave a little thought to how the page might work on a small screen:
https://xd.adobe.com/view/7a081799-3095-46c2-b22b-3b9f6393eb1d/screen/b2eb28d7-8e5b-40b4-8f1c-dbbcf479239f/Small-Screen

Let me know what you think about the proposed look and feel revision.  Thanks!

**Comment by benjanderson** [comment]
I saw the getting started page and wanted to give you my thoughts on it. 
#127

**Comment by corykon** [comment]
:+1: This is great stuff. I like the look and feel, feels very refreshed. 

A few thoughts: 
- A personal pref, I like "API" over "Documentation" for the component subnav, just because it's a little more specific.
- I'd love to make the examples section even more robust, perhaps have typescript/html toggles and a copy button when viewing the source, as well as syntax highlighting. (This could happen down the road for sure).
- Then in the "Documentation" section, I think we could tweak some of the verbage- "Component Parameters" are more accurately "Properties", and we should probably include the component's module name, selectors, and functions (if any).
