### ISSUE TITLE
Stackblitz examples don't work anymore

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#1395]
I get this error:
![image](https://user-images.githubusercontent.com/12416432/94197573-36110280-fe73-11ea-8095-830c9271cf44.png)

**Comment by andrew-frueh** [comment]
Did a little digging on this one, and unfortunately I think it's being caused by the bit integration.  What I'm seeing @joeskeen is that the dependencies don't seem to be loading on StackBlitz.  The reason that styles load is failing is being `@healthcatalyst/cashmere` hasn't been loaded.  And when it does try to load, this happens:

![Screen Shot 2020-09-29 at 3 58 32 PM](https://user-images.githubusercontent.com/22795893/94621383-67237580-026d-11eb-8b48-eb8c78fe0451.png)

Is there a way we can exclude the bit dependency in the StackBlitz template, Joe?
