### ISSUE TITLE
hc-tooltip does not work with disabled attribute on a button

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1476]
**Summary**

A button with an hc-tooltip on it doesn't show the tool-tip when it is disabled.
We have a few buttons with tooltips that have conditional tooltip values based on if the user has permission or not, but if the user doesn't have permission the tooltip is disabled. 
This previously worked with normal hc-pop functionality.

**Reproduction**

Steps to reproduce:

https://stackblitz.com/edit/hc-tooltip-conditional-with-disabled-attribute?file=src/app/tooltip-overview/tooltip-overview-example.component.html

In the component.ts file change the 'hasPermission' value from false to true to see the tooltip start working again on the 'very large tooltip' button.

**Comment by corykon** [comment]
As a workaround - would it be ok to wrap the button in a span and place the tooltip directive there? https://stackblitz.com/edit/hc-tooltip-conditional-with-disabled-attribute-gbaqdv

I want to say it is intentional that `disabled` turns off the tooltip, and that does seem like a reasonable feature to me, but the collision prob you're having with the button is pretty confusing... Maybe we could consider renaming the attribute in the tooltip directive to `disableTooltip` so that a tooltip can be placed directly on the button and not collide with the button's disabled attribute?

**Comment by Techgeekster** [comment]
Hmmm, yeah, I can see what you are saying.

I think it would be good if the 'disabled' attribute on the button element by default does disable the tooltip, but then having a 'disableTooltip' input that we can set to false to override the default functionality would be great and super simple.  It also would be a breaking change that way.

What do you think?

**Comment by corykon** [comment]
Yeah I was thinking the same thing :+1:  Have both `disable` and `disableTooltip` available, and then `disableTooltip` trumps the other to avoid the breaking change.

**Comment by Techgeekster** [comment]
I have determined it's not possible. The HTML 'disabled' attribute prevents the element from even triggering any events for us to grab.  There's not a way to do this, so we'll be using your workaround.  Thanks!
