### ISSUE TITLE
Table - focus on wrong checkbox cell after clicking different checkbox cell

### ISSUE THREAD

**Issue by Techgeekster** [HealthCatalyst/Fabric.Cashmere#1648]
**Summary**

After a table is loaded that contains checkboxes, after checking one of the checkboxes, when another checkbox is clicked the focus returns to the first checkbox clicked.  This is caused by the hcpop on the check box. Once the hcpop is removed the checkbox acts as it should.

**Reproduction**

![TableCheckboxIssue](https://user-images.githubusercontent.com/16390046/126272831-e7aec379-17f0-4f76-9a81-a0afc39c5358.gif)

Stackblitz reproduction: https://stackblitz.com/edit/angular-amltee?file=src/app/table-sort/table-sort-example.component.html

**Additional context**

When this bug happens on a scrolling table, it will scroll to the incorrectly focused element.  It has created major problems, but we are getting around it by using ngIf and ng-template with an hc-tooltip attribute.  It's hacky, and we'd like revert to using hc-pop once this is fixed.

**Comment by corykon** [comment]
I can help you on this one @Techgeekster. I think you just need to use `[restoreFocus]="false"` on the popover anchor (so in this case the checkbox) to avoid the focus jumping around. https://stackblitz.com/edit/angular-amltee-cjvbqr?file=src/app/table-sort/table-sort-example.component.html

Take a look at that and let me know if that feels like it solves the issue.

I think that's a property that needs to be made a little more prominent in the examples, because I've run into the same thing, had to dig into the docs to realize what was happening.

**Comment by Techgeekster** [comment]
I'm sorry, I just noticed this, I went on vacation starting Friday last week.
I'll try this out and get back to you, thanks Cory!  I hope it's this simple!

**Comment by Techgeekster** [comment]
Cool, that worked, thanks!
