### ISSUE TITLE
Using lodash

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#18]
We have discussed not allowing dependencies in Cashmere, but some pretty basic Javascript functions are not implemented for some browsers (i.e. IE) for example Array.find [(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)]

If we could use lodash then these problems will go away without us having to worry about polyfills and whatnot.

**Comment by benjanderson** [comment]
I am not opposed to allowing lodash. However, as this is mainly a UI library we wont have too much logic.

Is there a use case that you need it for @jacquie?

**Comment by ckeates** [comment]
![image](https://user-images.githubusercontent.com/10159523/35070236-db6ffcfc-fb99-11e7-998e-a583144ea327.png)

When I tried accessing the demo site via IE earlier, these were the errors I was seeing.  I am not sure if these were related to the components themselves or the demo site. If we are going to be using ES6 methods/features then we will need some solution for IE polyfills.

**Comment by joeskeen** [comment]
I do know why we are getting that error in IE, but it may be a matter of configuring what parts of `core-js` we are using (as this is already included in the project). See core-js documentation for `string.startsWith`: https://github.com/zloirock/core-js#ecmascript-6-string and `Array.find`: https://github.com/zloirock/core-js#ecmascript-6-array

IMHO if we can just use polyfills (which defer to the native browser implementation if present) for all use cases in the library, I would prefer not introducing another library.

**Comment by jtrujill** [comment]
I agree with @benjanderson and think we should avoid using any 3rd party library because of the possible conflicts that could occur for the person using our library and also to avoid bloat, since I'm unaware of how good all 3rd party libraries interact with rollup and/or webpack. I think our javascript should target es5 while our CSS targets CSS3. This way we can avoid polyfills or 3rd party libs. 

Because this is a component library I don't feel there will be a lot of need for underscore, lodash, immutablejs, ramda or whatever other lib there is.
