### ISSUE TITLE
When the Cashmere documentation page loads, many resources throw a 404

### ISSUE THREAD

**Issue by isaaclyman** [HealthCatalyst/Fabric.Cashmere#206]
Upon loading any page in the Cashmere components documentation, the following network requests fail:

![image](https://user-images.githubusercontent.com/9139369/38827364-eb6385e0-416f-11e8-8741-fe76897fb45e.png)

Although most say `ERR_ABORTED`, inspecting the Network tab reveals that they've all thrown 404 Not Found errors.

**Comment by joeskeen** [comment]
These are all font files... we'll need to check and make sure all are deployed when the CI/CD process runs.

**Comment by benjanderson** [comment]
You are using the old demo page http://cashmere.azurewebsites.net/home which doesn't have the fonts set to correctly serve. Please use the new demo site: http://cashmere.healthcatalyst.net

btw, this is an issue with IIS and can be fixed by adding something to the web.config. 
https://stackoverflow.com/a/25796999/810850
