### ISSUE TITLE
Documentation Generation

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#242]
Right now we don't have great documentation for Cashmere which requires that users of the library look at the source code to know what to use. Our current way of creating a demo component involves a lot of work and ends up not being very informative. As our components evolve, the documentation that we currently have will get our-of-sync with the code because we aren't generating our documentation from the code. 

I've been taking a look at several documentation generators and I think the one I like the most is Dgeni(Jenny). You use JSDoc style comments to document your code and you're able to process your documents with Processors to manipulate, filter or add meta-data about your documents. Dgeni also supports templates, and using the generated meta-data you're able to pick the template used for each document.

A good starting point would be to have each component author go through and document their code using jsdoc style comments and getting Dgeni setup with templates and processors. This would allow us to get some documentation out the door for developers to start using. To simplify the documentation and creating examples for a component, it would be best to replace http://cashmere.healthcatalyst.net/ with the generated docs from Dgeni. 

Initially we should keep the site very basic just to get documentation out the door for 1.0 release. Dgeni allows for you to use your own annotations and using that fact we could create an annotation which we'd attach to the share link of a stackblitz app. In the processor we could look for that annotation and generate an iframe with the source pointed to that stackblitz app. This would allow us to embed demo's of our components within our generated documents.

Documenting the library will be a top goal for me and I think that Dgeni is the tool to use. I would like to take on the task of getting Dgeni configured, but I'll need help with getting things documented. What are people's thoughts?

**Comment by jtrujill** [comment]
I think this goes into the conversation of separating the style-guide from Cashmere. I think initially that we should replace everything found at http://cashmere.healthcatalyst.net/  with the generated docs. 

The way I see this working is that along with generating the docs for each component, we would need to generate an index.html. This index would provide a menu for each of the docs and an iframe that acts as the main page's content. When a user clicks on one of the menu items, we would change the iframe's src to the menu item's generated html. 

Later when we have time or even when we do the app restructure we could pull our demo app into it's own repo and use that for our style-guide app. The end-goal would be to load those generated docs into the style guide under components and render the html within our angular app. This would require that we push the generated docs from Cashmere into a github repo. Then during publishment of the style-guide we would pull the latest artifacts from the Cashmere docs repo and publish those docs along with the style-guide to github pages.

**Comment by andrew-frueh** [comment]
Okay that makes sense for short term and long term.  Perhaps even in the short term version we could still keep a version of the home page though.  I think it's valuable if we're pointing someone to Cashmere for the first time that we at least have an introduction before we launch them into the content.

**Comment by benjanderson** [comment]
If I understand correctly, you proposing to scrap the current http://cashmere.healthcatalyst.net/ site and replace it with a doc site? Looking up dgeni here is a static site generated with that tool
http://wingedfox.github.io/dgeni-alive/docs/angular-route-segment/#/api

for context, it was generated from the following code
https://github.com/wingedfox/angular-route-segment/blob/master/src/route-segment.js

Step one would be document a single component and get a basic site generated. Eventually all the components would be documented and hopefully have a link to a stackblitz

Correct me if I am wrong, as the following are assuming this is what you meant. When we originally created the site we based it off of angular materials site:
https://material.angular.io/components/chips/overview

Quite a bit of work has gone into this site and it would be discouraging to scrap it all. Plus it was neat to have non developers have a place to go and it was exciting to show off what cashmere was. This would be very discouraging to the project, especially when interest has been lacking quite a bit.

I really like the idea of generating documentation, you dont have to sell me on that. I would like something in between where we kept the layout of the existing demo site and embedded documentation in each of the components. 

On another note, I would love to have live coding much like this angular library doc site does
https://wykks.github.io/ngx-mapbox-gl/demo/edit/add-image-generated

**Comment by andrew-frueh** [comment]
I have a proposal for how we might be able to have our cake and eat it too on this one.  Jeremy makes a fair point that trying to pull together the generated docs into the existing site is a non-trivial amount of work, so that's why he's suggesting we have a clean site for them.  But the rest of the group has expressed concern about losing the current content on cashmere.healthcatalyst.net, which I echo because I actually use the things like the hex values in the styles section pretty regularly.

So what if we create a new domain like cashmeredocs.healthcatalyst.net for now, and we use that as the location for the generated dgeni docs.  I've attached html and css that can be used for degeni index and template files which look identical to our current cashmere demo site (no responsive capability, but I can add that later).  We could change the URL of our components button to go to our new domain, and the navbar links in the attached index file will jump back to the current demo site.

This way we get a clean slate for the generated component docs, but the rest of the site remains intact.  Thoughts @benjanderson @corykon @corytak @jtrujill ?

Also Jeremy, let me know if you need me know if the attached html will work for you to retrofit into dgeni templates or if you need me to make any changes.

[Dgeni.zip](https://github.com/HealthCatalyst/Fabric.Cashmere/files/1996792/Dgeni.zip)

**Comment by corytak** [comment]
@andrew-frueh I checked out your dgeni template and it looks really good. The only thing I would like to think more about is the size of the embedded stackblitz-- I found it difficult to view the preview pane.

Also I've been trying to think about a good way to keep the stackblitz demos we build up to date with our components. It seems like that if there's an api change to a component it would be pretty easy to forget about the accompanying stackblitz. 

Currently, I use the styles tab all the time for looking at colors now so I wouldn't want to lose that, but I think we could itemize our components and start the work of writing the jsdocs one at a time and gradually phase those over. I agree with @jtrujill about splitting out the styles into a separate repo. I'm a little fuzzy about implementation details (separate npm package for each used by one parent project?), but like the idea of having a cashmere umbrella site/landing page. From the landing we could link out to our styles, angular component library, and any other endeavors that may fall under cashmere. e.g. have the same domain for all of our sites so that it looks like a fluid web experience for an end user, but manage them all as separate repos/projects.

**Comment by jtrujill** [comment]
I'm sure the styles page doesn't contain much angular code and could easily be extracted into an html file and linked to the index file that we'd use for the Dgeni docs. It'd be confusing to have two different sites each with it's own documentation. This would just be an intermediate step on our way to having a style-guide site, which would just be our current demo app, that would integrate better with the generated documentation

**Comment by corytak** [comment]
@jtrujill I think I understand what you're saying and it sounds much simpler than creating an umbrella repo, angular component library repo, and styles repo. To clarify we would convert our current styles pages into a static web page that includes a link to our generated docs from the angular library?

**Comment by jtrujill** [comment]
@andrew-frueh The templates look good. 

Next we'll need to talk about the public interface of our components and how documentation will work. It's common with libraries such as these to have a naming standard for things which are private. The standard is to prefix methods and properties with and underscore. This will be needed because we need to filter those elements out that are private so that documentation is generated for them.

**Comment by corytak** [comment]
@jtrujill regarding prefixing private properties and methods with an underscore that is a [direct contradiction from the angular team:](https://angular.io/guide/styleguide#style-03-04) I'm okay deviating from standards for a purpose, but I want to make the decision of deviating from a community standard/best practice consciously. 

Since we're using typescript, would it be possible for dgeni to recognize the keyword `private` rather than relying on an underscore?

**Comment by jtrujill** [comment]
@corykon What I'm wanting to do is replace everything found at https://cashmere.healthcatalyst.net with the static html files that are generated from Dgeni along with a styles page. There's a lot of work with getting the generated docs into the current app, work that needs to be spent in other places.

Again the app is not being deleted from the repo. The only thing that will change is what gets published to the github pages repo used by https://cashmere.healthcatalyst.net.

**Comment by jtrujill** [comment]
Their style guide is not target for framework developers. I'm familiar with the standard and I'm a huge supporter of standards. Also just because something is public doesn't mean it should be a public API for users to use. Angular requires that any property or method that is used in the template to be public but that doesn't mean it should be available for the user to call. That is why an underscore is used in so many libraries to mark elements as private

**Comment by andrew-frueh** [comment]
@corytak - I completely agree with you on the StackBlitz iFrame.  I was struggling with that too.  It's a tough problem to solve because we don't want to take up so much space that the API documentation gets buried, but it needs enough space that you can actually use it.  Over on Angular material they split their component pages into API and Examples, which @jtrujill and I were thinking we might be able to avoid.  But if it's all getting too squeezed, that might just be how it needs to go.  Totally open to suggestions here.

@jtrujill - for most of the styles pages you're probably right, although the [Charts section](https://cashmere.azurewebsites.net/styles/chart) uses a whole lot of Angular and D3 and would be a pain to port back to straight HTML.  Since we're talking about a stopgap solution right now anyway as you said, wouldn't it be easier to leave those pages alone and just link to them in their current location?  Having two URLs isn't ideal and isn't a long term solution, but turning Styles into HTML isn't either - so why create extra work for ourselves?

**Comment by jtrujill** [comment]
@andrew-frueh what if we get the style-guide repo setup and comment out the components tab content and link to the Dgeni docs? I feel that's a good compromise between the different interests

**Comment by andrew-frueh** [comment]
Yup - I agree that would be a good compromise, and it's not throw away work that way either.  Sets up the foundation for the long term solution.

**Comment by jtrujill** [comment]
Awesome I'm going to be reading up on Dgeni to get very familiar with this and hopefully I can begin work on the processors sometime next week

**Comment by corytak** [comment]
@jtrujill thanks for leading this up. I'm happy to help out by being a workhorse to write up the jsdocs for some components.

**Comment by jtrujill** [comment]
Thanks. It'd be best to have all original authors of a component go through and get some initial comments going, since they'll know the components best

### Things that'll need documenting

- Component overview with examples of how it's used
- @Outputs and properties(@Inputs) 
-  Methods that are part of the components API

### Things that don't need documentation

- Methods and properties that aren't part of the component API (private access modifier isn't enough to signal that it's an implementation detail)
- Angular lifecycle methods
- Abstract classes or interfaces not used directly by a user

### Things that need to happen

- Add underscore to methods and properties that aren't part of the components interface(private isn't enough because Angular requires any property or method that's used in the template to be public)
- Create a StackBlitz demo for each component that demonstrates all the different uses of the component(I'm thinking that it'd be best to have one demo per component than multiple)

All of this documenting can happen ahead of me getting things pushed out for Dgeni and this process can be very incremental. I'm going to get some more research done for the particular annotations that should be used and I'll post back here with the details

**Comment by jtrujill** [comment]
So I've been taking a look at what we could do and I'm thinking that to save time on this document generation we could use what angular material has and just modify it for our needs. Sounds good? Should we also use their templates as a base? 

With the way their Dgeni docs work is that it'll group components under the same root directory in order to avoid having their docs for a single component scattered. I can get a PR put together that uses their templates and maybe we'll just modify those along with using our own stylesheets
