### ISSUE TITLE
Most "Last updated" dates on demo site reflect last pull request

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#248]
Currently most the "Last updated" dates are May 14 based on the latest pull request. This is not at all accurate and we should either find an automated solution or remove that date...

![image](https://user-images.githubusercontent.com/1934453/40026662-76e26f6c-5793-11e8-96c8-4aee9d1a52e8.png)

**Comment by jtrujill** [comment]
I'd be for removing that feature. If developers care about that they can use git or even GitHub to see when a directory was changed

**Comment by andrew-frueh** [comment]
Yeah, I noticed this a little while back too.  I think there is some value in being able to see easily how stale a component is - although Jeremy is right that you can dig a bit on GitHub to find that information.  With the generated version of our docs, is this something that could be easily fixed?  @jtrujill does Dgeni have some kind of variable like {{ lastModifiedDate }} or something like that we could drop in?  If not, then I think it's okay to remove this line.

**Comment by jtrujill** [comment]
This introduces a whole new set of concerns. How should we host documentation for the different app versions? Should we allow the user to select what version of documentation they want or should we only care about latest? If we only care about latest then I don't think we should be concerned with when a component was introduced.

I'd just like to say that hosting multiple version of the app would introduce a lot of complexity. That maybe we want to stay away from. Especially since there aren't many contributing
