### ISSUE TITLE
Separate Dev guides from User Guide app and update Dev guide

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#325]
We need to update our contribution guide so that it talks about best practices, how to submit issues, ask for feature requests, PR submission guidelines and commit message convention.

As an example here is what Angular materials contributing.md looks like https://github.com/angular/material2/blob/master/CONTRIBUTING.md

Also we should remove all of the ::: from the file. It doesn't belong in the userGuide app since it's intended for users of the app, who are developers, but they aren't developing for Cashmere. Instead we should do the standard of either keeping it at the root or creating some kind of docs directory

**Comment by benjanderson** [comment]
Thanks for creating this relating to the issue I created #320

Its funny you mention the material repository, they do have a guides directory https://github.com/angular/material2/tree/master/guides , so I would be ok keeping it. However, I do think having a `CONTRIBUTING.md` in the root does make it more visible and seems to be more of a standard. Cashmere is based off the material project and it does look like they have a guides page similar to ours: https://material.angular.io/guides . That said, I am for keeping the the ::: markup, I think it adds a nice style to demo site. I am a little biased because I introduced it and would love to hear others feedback

**Comment by jtrujill** [comment]
If you look at their guides it's centered around the user's of the library and not developers of the library. I think that's an important distinction that we should follow.

The user guide app is geared towards users of the library. For that reason we should create the HTML we want within the user guide app and not in markdown. The reason I hate the triple colon is that it's difficult to tell which pairs belong to each other and when you view those docs on GitHub or any other markdown renderer it shows as :::

It's standard to create markdown docs which developers can follow either on GitHub directly or using their ide to read the necessary documents.

I have a PR to expand the contribution guide and if we agree to move forward with keeping Dev guides out of user guide app I can take this task on since it shouldn't be difficult.

**Comment by jtrujill** [comment]
@benjanderson @andrew-frueh Any input? I'd like to keep the UserGuide app centered on documentation of the use of the library and keep dev docs separate. We can link to a dev getting-started.md on the cashmere.healthcatalyst.net site if we want.

For the documentation that would remain in the UserGuide app like User Feedback, getting-started(user of library) and supported browsers, I could create actual html that gives the same look that we currently have

**Comment by benjanderson** [comment]
I am all for standardizing what the general standard is but I think their needs to be a line drawn. We need to weigh the effort conforming to an ever changing standard and spending our time re-writing code verses leaving it as is and works well. Cashmere is almost exclusively going to be used by health catalyst developers, so our audience is quite a bit more narrow. Plus that effort could be spent actually improving the components themselves

**Remove all of the ::: from the file**
I'm not attached to them, and would be ok with this. I do however stick with my original opinion that they bring a good style. 

**Move developer guides to root**
I think this does make sense, we could even remove the :::

**Move markdown guides to html**
You have brought this up a few times, and I think it comes down to that line of where we spend our time. I am ok, if you did this, especially since you seem very passionate about it. I think its acceptable as the end result will be the same.

**Comment by benjanderson** [comment]
I should have said best practices instead of standardizing. 

I would vote to keep them as markdown and remove the ::: if its a choice between markdown and html 

You make good some good points, and I appreciate all that you do. This project would not be as far without your efforts. I try to actively participate in conversations because care and want to show my support.
