### ISSUE TITLE
Migrate progress indicator "Special Usage" to a guide

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#356]
**Describe the problem this feature request is solving**
Auto generated docs won't preserve all the goodness that used to be in the progress docs markdown file

**Describe the solution you'd like**
Migrate the missing stuff to a guide

**Describe alternatives you've considered**
Find some other way to preserve the info... like allowing additional markdown... maybe do that in the future

** If any, which components will have to change, and how **
None

*   Components changed?
*   Are these breaking changes to public interfaces?
Nope

**Additional context**

**Comment by jtrujill** [comment]
If it's needed we can do an overview for each component. I can resurrect the markdown files I deleted and move them into the components directory. Then I can run a markdown dinner over it. This would require that the markdown files be cleaned up since they contain stuff covered by dgeni and the examples project.

I can take this on and get it done real quick; however I want #355 to be merged first

**Comment by corykon** [comment]
@jtrujill allowing for additional markdown would be awesome! way better experience than digging around for related guides in other section of the site

**Comment by jtrujill** [comment]
I'll plan to bring those markdown files back once that PR is done
