### ISSUE TITLE
Docs Examples - code blocks don't have line numbers

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#375]
**Describe the problem this feature request is solving**
In the Examples section of a component's docs, when viewing the "HTML" or "Typescript" for a given example, for readability the code blocks should have line numbers.  Our markdown generated code-blocks that @benjanderson built are a good target for the styling.

**Comment by jtrujill** [comment]
@andrew-frueh After taking a look at this, it looks like the only way to add line numbers is to use jquery along with a [plugin](https://github.com/wcoder/highlightjs-line-numbers.js/). JQuery is a large library and I'm not sure it's worth doing. The implementation would also be a little odd since we'd have to load up the HighlightJS generated html file, and after it's loaded and we've set the content on the page we'd have to run the JQuery plugin on the content.

I tend to agree with the dev of [HighlightJS](http://highlightjs.readthedocs.io/en/latest/line-numbers.html) on this matter. If we keep our demo code blocks very small it doesn't seem worth it, which is what I've been suggesting. I also wonder what benefit the user gets from having those line numbers. What truly makes the demo easier to read is keeping it focused only on the component you are demoing. I think it's a good suggestion by the HightlightJs dev that, if needed, to include comments within the code itself rather than relying on line numbers.

@andrew-frueh @benjanderson @corykon What benefit do you see from doing this and would it truly be worth it.

**Comment by corykon** [comment]
I'm good without line numbers
