### ISSUE TITLE
Naming Conventions Guide

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#411]
**Describe the problem this feature request is solving**
As per the discussion that was started in #392, we need to introduce at least some lightweight naming conventions around our sass classes.  @jtrujill proposed a structure that @corykon followed for the typography additions in that PR.  To keep everyone on the same page, we should have a guide that explains our naming conventions both for sass and for components.

**Describe the solution you'd like**
Add an additional markdown file to our guides that describes naming conventions for contributors to follow when adding styles or components.

**Describe alternatives you've considered**
Could be added to the "Getting Started" guide, but I feel like this is really its own subject.

** If any, which components will have to change, and how **
It would probably worth going back through and auditing our existing styles and components to ensure that they are following the conventions outlined in this guide, but that could be a separate PR.

**Comment by jtrujill** [comment]
@jacquie has suggested that we use [BEM](http://getbem.com/naming/) for our css, but I think that's a bit heavy. I like a variation that I've been using in my components where I have the following:

`{company-scope}-{block-modifier}-{element}`

For example in `hc-form-field.component.scss`, I have the following definition `.hc-form-field-label-wrapper`. If we break that down into it's individual components it'll make more sense:

- company-scope = hc
- block-modifier = form-field (component name)
- element = label-wrapper (css put on element within the component)

The way this works is the following
- company scope scopes all of our css to our company
- block modifier is an element that can standalone within our company scope.
- element is element that can't standalone and requires the block modifier.

I hate the separators that BEM uses and I prefer hyphens to separate out the different scopes(company, block element and element).

**Comment by jtrujill** [comment]
When it comes to css definitions for what is being called the typography feature of Cashmere, I had left on comment on this subject in a previous [PR](https://github.com/HealthCatalyst/Fabric.Cashmere/pull/392#issuecomment-411450769)

**Comment by jacquie** [comment]
Yeah, I agree about the BEM separators - I know they serve a purpose, but they are ugly and too complicated 😱 - I like @jtrujill 's variation :)

**Comment by jtrujill** [comment]
When it comes to giving names to our components, I've decided that I really hate having the Directive and Component suffixes. You end up with things like RadioButtonComponent or RadioGroupDirective, which for the user has no benefit and makes the component name longer. 

I'm not sure where I stand with prefixing our components with Hc so that RadioButtonComponent would become HcRadioButtonComponent. The chance of a collision with another RadioButtonComponent is slim and with es6 imports you can use the following `import {RadioButtonComponent as <something-else>}` so this avoids conflicts.

I kinda like the component file naming scheme since you can easily search for a file but I also feel that the file extension does the same thing. We aren't going to have multiple scss, html or ts files for a single component, so it's not really necessary. I could go either way with this standard

**Comment by jtrujill** [comment]
If we can get this nailed down I can get started on a contribution guide specific to the naming standards.
