### ISSUE TITLE
The dialog and button (in the background) have the same z-index on Opening the dialog

### ISSUE THREAD

**Issue by shlok297** [HealthCatalyst/Fabric.Cashmere#446]
**Describe the bug**
Bug with Operations Console :
the dialog and "with Options" have the same z-index

Steps in Operations Console:
Go to Job Definitions page
click on run for any job listed
click on "with options" button
error: the dialog and the "with options" have the same screen depth

**Expected behavior**
the "with Options" button should be blurred or covered with the translucent black image

**Screenshots**
https://user-images.githubusercontent.com/31379055/44119389-4b0f7a8e-9fd6-11e8-8181-e73de05c1cb0.png

**Comment by jtrujill** [comment]
I took a quick look at this and the issue is that the modal and the popover are in the same [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) If we wanted to correctly solve this we would want to place any overlay elements within a div that is in the body of the html page. Then we'd set a very high z-index value on that div. By ensuring all overlay elements are within the same stacking context we can set reasonable z-index values for our overlay elements. It'd be best to put the z-index value in some global scss file that makes referencing it easy. Until then, a quick fix could be to just increment the z-index of the modal to something higher. The popover seems to have a z-index of 3000. 

Here's an example of how stacking contexts work. https://cashmere-demo-s5axz9.stackblitz.io. If you take a look at the app.component.scss, I'm setting the z-index: 1 and using the property `opacity` to trigger a new stack context. I'm effectively creating a stacking-context that'll guarantee that anything within the app itself will have a lower visual z-index than the modal. You could increase the z-index of that popover to the highest value and it'll remain below the modal
