### ISSUE TITLE
Make split button more flexible (by creating hcButtonGroup)

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#447]
**Describe the problem this feature request is solving**
I want to have more freedom with the way the popover from a split button works or looks. As it stands I don't have access to it. Specifically I needed to style the contents of a popover in a way that using hcButtonItems wouldn't allow, and I wanted to position the popover differently.

**Describe the solution you'd like**
Create a new hcButtonGroup, that can contain any number of buttons, and give me an easy way to construct my own split button with a custom popover. Maybe something like this:

```
<hcButtonGroup>
     <button hc-button buttonStyle="primary">Main</button>
     <button hc-button buttonStyle="primary" [hcPopover]="options" popperPlacement="bottom-end">
          <hc-icon fontSet="fa" fontIcon="fa-chevron-down" icon-sm></hc-icon>
     </button>
     <hc-popover-content #options>
         <ul class="list-options">
             <li><a href="https://healthcatalyst.com/">Health Catalyst</a></li>
             <li><a href="https://community.healthcatalyst.com/">Health Catalyst Community</a></li>
         </ul>
     </hc-popover-content>
</hcButtonGroup>
```

Could use this type of construct for something like this:
![image](https://user-images.githubusercontent.com/12416432/44159639-42f88080-a075-11e8-85f6-0b7e89ebfb6f.png)

And, could refactor the pagination control to leverage this.

**Describe alternatives you've considered**
Noneski, but I'm open to suggestions.

**If any, which components will have to change, and how**
Maybe depreciate split button?

**Comment by jonest** [comment]
Tangentially related, but on Ops Console we're considering moving away from the split button because of how much space it takes up. I wonder if we can make it more flexible by allowing us to just have a list of icons and some sort of expander for additional options.

![image](https://user-images.githubusercontent.com/3075414/44159815-c914c700-a075-11e8-8b28-f648c28aa3d1.png)
I think we'd like to have the run button here be just a play button with some sort of arrow for a dropdown to show the "run with options" popover. Then this button group would be several icons that could collapse into something like a hamburger.

We may just need to rethink the UI to just have a menu like in VSTS, but I think we all would like the ability to go straight to run without going through a menu.

![image](https://user-images.githubusercontent.com/3075414/44159969-30cb1200-a076-11e8-873f-65b23640ac36.png)

**Comment by andrew-frueh** [comment]
Love this idea @corykon - this adds more flexibility while preserving functionality.  The only thing to think about with a button-group replacing a split-button is that the dev would need to be able to specify a pixel value/percentage of how much horizontal space each item in the group takes up.  Like by default they would be equal, but in a split button the right side options arrow would only have 30px or something like that.  Thumbs up from me.

**Comment by jtrujill** [comment]
@corykon could you explain what style you're trying to achieve? Are you just trying to have a list of buttons that are squished together and on click you display a popover?

**Comment by andrew-frueh** [comment]
This is kind of getting into a UX discussion @jonest - but consider that if you change the "Run" button to an icon, it then has the same visual weight as all the other buttons in the row.  Which is to say that none of them are more "important" than any other, or grab the user's eye more than any other.  I think that's the benefit of keeping Run as a primary button even though it takes up more space, but it's the primary action a user would take in that row.

**Comment by corykon** [comment]
I think there are lots of good uses for a button group, but in particular this something I wanted to recreate:

![image](https://user-images.githubusercontent.com/12416432/44161999-2ca1f300-a07c-11e8-9b16-c71117321b98.png)

Things I wasn't able to do (at least not easily): 
- have the popover right aligned with the button (because the button is on the right side of the page and just looks nicer that way)
- a full length background hover effect on the menu item.

**Comment by jtrujill** [comment]
@andrew-frueh what does the style-guide have for the split button. I don't remember what I was going off for the split button. I think the menu @corykon has looks better than our default. Rather than introduce a new component for the above case it'd be better to have things standardized.

I see this as being two separate requests: one to update the style of split button and another to introduce grouped buttons. Do we have anything in the style-guide about buttons that are styled like bootstrap's button group? 

For the split-button, we should encapsulate the implementation of the menu more than what was suggested. I'm going to be moving away from the hcPopover implementation and using what's available in the `@angular/cdk` I don't know if it makes sense to allow the user to align the 

```
<hc-split-button buttonStyle="destructive">
    <hc-main-button>
      <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
      Save
    <hc-main-button>

    <hc-button-menu>
      <div hcButtonMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
        <div>Save</div>
        <span>Alt + S</span>
      </div>
      <hc-divider hcButtonMenuItem></hc-divider>
      <div hcButtonMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-download"></hc-icon>
        <div>Export patient list</div>
      </div>
    </hc-button-menu>
</hc-split-button>
```

We also need to think about what buttons are allowed in button groups. It doesn't make sense to allow split-button, but maybe it makes sense to allow plain old buttons, hc-button and hc-icon-button. We'd need to override the styling so they didn't introduce their own padding or whatever.

@corykon If you want to take on the button group, I can take on editing the split button. However, this will introduce a breaking change. How do we want to handle this?

**Comment by jtrujill** [comment]
@andrew-frueh this is the current look of a split button
<img width="234" alt="screen shot 2018-08-15 at 11 52 58 am" src="https://user-images.githubusercontent.com/5596515/44163870-cae48780-a081-11e8-9f78-0cbf651ce49f.png">

I like the menu that cory provided which is more of a menu style. What should be the default style. Should we even allow an alignment of the menu or should they all follow a similar pattern

**Comment by jtrujill** [comment]
Maybe that menu should be extracted into it's own component to cover the split button but also to cover @jonest case. That way an hc-icon can be tied to an hc-menu

**Comment by andrew-frueh** [comment]
@corykon and I took a look at this together yesterday, and I actually never really defined the look of the split button's dropdown.  As usually, Cory's stuff looks great - so I'd be fine with making that the new standard.  Would we want to be that opinionated about the dropdown content though?  Or should we leave it as more of a flexible space where the user can define how the content of the dropdown is styled (assuming they'd usually just follow our standard - using `hc-list` or however Cory is doing it)?  Seems like that's how you've steered us more towards with our other components @jtrujill - like the drawer for example.

And regarding button groups - that's new territory as well.  Currently nothing in our style guide defining a look for that.  So I'm happy to give @corykon the reigns to define that style keeping it in line with everything else we currently have going on in Cashmere.

**Comment by jtrujill** [comment]
I like the idea of maybe extracting a new hc-menu item which provides a good style basis but that easily allows a user to override that styling. I'm thinking that I'll go with an hc-menu because that'll cover two cases presented here. I'll be levering the `@angular/cdk` for the menu overlay part. 

@andrew-frueh I try to plan for as much flexibility as possible but I did drop the ball with this split-button. With this design it'll allow users to style the hc-menu-item however they want, so they should be able to do full length highlighting or whatever.

Anyways here's what the html would look like

```
<hc-split-button buttonStyle="destructive">
    <hc-main-button>
      <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
      Save
    <hc-main-button>

    <hc-menu>
      <div hcMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
        <div>Save</div>
        <span>Alt + S</span>
      </div>
      <hc-divider hcMenuItem></hc-divider>
      <div hcMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-download"></hc-icon>
        <div>Export patient list</div>
      </div>
    </hc-button-menu>
</hc-split-button>
```

If we wanted to make this even more powerful I could abstract this even more so that you need to provide your own menu-trigger and it would look something like this

```
<hc-split-button buttonStyle="destructive">
    <hc-main-button>
      <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
      Save
    <hc-main-button>
    <hc-icon fontSet="fa" fontIcon="fa-arrow-down" 
       hcMenuTriggerFor="menu"
       hcButtonMenuTrigger>
     </hc-icon>
    <hc-menu hcButtonMenu #menu>
      <div hcMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
        <div>Save</div>
        <span>Alt + S</span>
      </div>
      <hc-divider hcMenuItem></hc-divider>
      <div hcMenuItem>
        <hc-icon fonSet="fa" fontIcon="fa-download"></hc-icon>
        <div>Export patient list</div>
      </div>
    </hc-button-menu>
</hc-split-button>
```

Do we want this kind of of flexibility or should I be more strict with the design

**Comment by corykon** [comment]
Some more thoughts:

- @jtrujill I think the version with the custom menu-trigger would be pretty sweet.

-  What if we refactored the popover to use the cdk's overlay stuff? I feel like that's something we'd talked about doing before.

- I'm in favor of making things as flexible and composable as possible. Split button could just be an hcButtonGroup that holds an hcButton and an hcIconButton, then we use the popover component we already have, and then nest some hcMenuItems in that popover if that's what's needed, or use hcList, or do something totally different.

```
<hcButtonGroup>
     <button hc-button buttonStyle="primary">Main</button>
     <button hc-icon-button buttonStyle="primary" [hcPopover]="myMenu" popperPlacement="bottom-end">
          <hc-icon fontSet="fa" fontIcon="fa-chevron-down" icon-sm></hc-icon>
     </button>
</hcButtonGroup>
<hc-popover-content #myMenu>
       <div hcMenuItem>
             <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
             <div>Save</div>
             <span>Alt + S</span>
       </div>
       <hc-divider hcMenuItem></hc-divider>
       <div hcMenuItem>
             <hc-icon fonSet="fa" fontIcon="fa-download"></hc-icon>
            <div>Export patient list</div>
       </div>
</hc-popover-content>
```

With that kind of flexibility, I could do something crazy custom like this:

![image](https://user-images.githubusercontent.com/12416432/44169779-bd83c900-a092-11e8-88d6-663a2174e53a.png)

**Comment by andrew-frueh** [comment]
Just catching up on this thread - I think that markup @corykon is proposing looks great and I can't think of any design needs that wouldn't accommodate.

**Comment by jtrujill** [comment]
Again spli-button and button-group serve different purpuses. Split button needs to perform verifications on it's projected content. Button-group is essentially just there for case purposes. Maybe making sure certain buttons aren't used. It would be a bad idea to mix the two.

Popover is a generic popup while hc-menu would be a pop up styled as a menu.

@corykon There have been talks of converting popover to the cdk and I'll leave that for Ben or when I have a chance to

**Comment by jtrujill** [comment]
I think that we should really think about this. The bootstrap example you showed for button group at the top is the styling I thought you were wanting to imitate. I think it's less intuitive and odd to have a button group function as both a split button component and as a grouping of button elements that have a style similar to this
<img width="243" alt="screen shot 2018-08-15 at 4 42 21 pm" src="https://user-images.githubusercontent.com/5596515/44177235-35a9b900-a0aa-11e8-90d8-90415634a3bf.png">

Bootstrap follows what something similar to what you're proposing, but I don't agree with it. We need to think about whether it make sense to have more than one action button along with the toggle button? If that's the case than I'd say maybe this would be the way to go. 

```
<hcButtonGroup>
     <button hc-button buttonStyle="primary">Main</button>
     <button hc-button buttonStyle="primary">Another Button</button>
     <button hc-icon-button buttonStyle="primary" [hcPopover]="myMenu" popperPlacement="bottom-end">
          <hc-icon fontSet="fa" fontIcon="fa-chevron-down" icon-sm></hc-icon>
     </button>
</hcButtonGroup>
<hc-popover-content #myMenu>
       <div hcMenuItem>
             <hc-icon fonSet="fa" fontIcon="fa-floppy-o"></hc-icon>
             <div>Save</div>
             <span>Alt + S</span>
       </div>
       <hc-divider hcMenuItem></hc-divider>
       <div hcMenuItem>
             <hc-icon fonSet="fa" fontIcon="fa-download"></hc-icon>
            <div>Export patient list</div>
       </div>
</hc-popover-content>
```

I would say that other action should probably be in the menu. @corykon what are you hoping to get out of eliminating split button and using hc-button-group?

I think we should put our designs away for a moment and define what it is we need. @andrew-frueh this is where you will come in. We need to know what we need in a split button and we need to know what a button group is and how it should function.

**Comment by corykon** [comment]
This has been superceded by #453

**Comment by jonest** [comment]
> This is kind of getting into a UX discussion @jonest - but consider that if you change the "Run" button to an icon, it then has the same visual weight as all the other buttons in the row. Which is to say that none of them are more "important" than any other, or grab the user's eye more than any other. I think that's the benefit of keeping Run as a primary button even though it takes up more space, because it's the primary action a user would take in that row.

This is kind of where we were discussing having only a couple buttons that people would likely be using as icons and the rest hidden under a hamburger.

Thoughts on something like that @andrew-frueh ?
