### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#46]
We outlined a date picker in the style guide - which I think may have been implemented by Safety Surveillance and or Leading Wisely.  The actual version built in the apps may look or function differently.  This was the suggested use information:

"Determining whether or not to include a date picker should be determined by the usage of the app. If dates are within the current or upcoming year or if date ranges usually only extend 30 day durations using the calendar icon and the calendar popover is advisable. In situations where dates are longer or further in time simple text input would be better."

**Date Picker Spec from the Style Guide**
<img width="952" alt="datepicker" src="https://user-images.githubusercontent.com/22795893/35476034-78b486ee-0366-11e8-8f75-dbfb33957217.png">

**Comment by andrew-frueh** [comment]
In looking at this, it will probably make the most sense for the "Select date" box to use the component from #14 - especially since @jtrujill is designing it to allow for a glyph to be included on the right side.

**Comment by jtrujill** [comment]
I'll be taking a stab at designing this datePicker, but I'll need to find a consensus on what it is we need in a datepicker. I see the following being necessary:

- Custom date filter that a user can set. This would allow the datepicker to pass a date into the filter to see if it's a valid date. If not then the ui would disable that date for selection.
- minDate and maxDate
- Ability to set a startDate
- Maybe format the date according to a region? (do we want to have a dependency on moment) We might be able to get around that by having the dependency be optional and requiring that the user provide the dependency using an Injection Token that we have defined

The rest of the design of the datePicker is UI related, but I believe that with those basic abilities all cases could be covered for the datePicker. Rather than have a single input which does a date range that the user can set, I believe it'd be best to have it be split between two datePickers. 

One reason for the split is that I'd like to have the from and to date split at the model level. The datePickers will be backed by an input element and, rather than have to process a string to split the from and to date, I'd rather have that already be split. 

The second reason is that you end up with a more complicated design. When you are handling two dates(from and to) what does the minDate and maxDate indicate? Is it for both the from and to dates? Does that mean we have to introduce two more min/max to accommodate this so we have the following: toMinDate, fromMinDate, toMaxDate, fromMaxDate? Do these names make sense when it's not a range? This leads to the question of having two datePickers: datePicker and dateRangePicker.

**Comment by jonest** [comment]
Two pickers might be a good idea if there are teams that need it, but currently I believe Ops Console simply needs the range. A min date would probably be good to prevent users from creating a job that may never start.

We'll also need time, but we should be able to make that available in another selector. I wonder if we would want another component for that as well or if it should be something included in the date picker.

**Comment by jtrujill** [comment]
Adding time complicates things. How would we format that. I think working with iso 8601 date format is the easiest, but we don't want to display that to the user. Because the date and time would be put in an input element that the user could edit what would the time component look like? Say we wanted to pick Aug 15 @ 2:00pm would it format as the following:
08/15/2018-2pm
I can't think of any pickers where the time is included in the datePicker. There's a whole other component of complexity to adding time. I believe it'd be easiest to split them into two different components. That way we could easily add onto the timePicker component without adding complexity to the datePicker. We would essentially have completely different interfaces and logic and it doesn't feel right to have them all within one component.

**Comment by jtrujill** [comment]
For the time component maybe we could borrow from the android design?
![android-time](https://user-images.githubusercontent.com/5596515/44159051-92d64800-a073-11e8-961f-c5f7aa6ed042.jpg)

**Comment by TonyCurtisLives** [comment]
Ops console does need a date picker, a date range picker and a time picker. So any of these would be great!

**Comment by j2jensen** [comment]
So far in Pop Builder we've found that the traditional "date picker" (as in something that shows a calendar for the user to click on) doesn't actually make sense for the way we expect users to think about the dates they're inputting. We're in the category mentioned in the style guide, where users are likely to have a pretty specific idea of the date that they're going to choose (maybe even copy/pasting it out of a document they're looking at), and that date will frequently be a year or more in the past. They're not likely to care about things like which day of the week the date they choose falls on.

So we ended up with a simple text input that converts the user's entry into a date with the Sugar Date javascript library. That allows it to deal with both simple formatting issues (2018-8-4 vs 4/8/2018) and very complex ones ("8/4", "August 4, 2018", and "three years ago"), which can be real crowd pleaser.

Regarding separation of the different pickers, I think a componentized approach would be good. Start with a Date picker. A Date Range Picker is a separate component that should show two separate DatePicker inputs. It makes sense for this to be its own component (as opposed to just telling devs to use two Date Pickers) because it can manage interactions between the two dates. It would make sense for the Date Range Picker to not allow the end date to be before the start date, for example. And that component would probably have minStartDate/maxStartDate/minEndDate/maxEndDate settings, which just pass through to its subcomponents' settings. If you want the Date Range Picker to be able to show the other selected date and highlight the dates in between one and the other, you'll need to add a few features to the original Date Picker (or maybe have both components leverage a third, lower-level component that has more options but is harder to set up?). 

A Time picker can likewise be its own standalone component, but with a DateTime Picker as a separate component that includes a DatePicker and TimePicker component, and possibly even a DateTimeRange Picker (for things like an appointment in a calendar that might last longer than a day).

Also, HTML5 defines some date and time input types. They have limited support from various browsers, and they're frankly pretty ugly in desktop scenarios, but they use native pickers for mobile devices, which can be a much better experience when you're trying to enter information with a phone. I don't think any of our current use cases involve mobile devices, but it's good to keep that in the back of your mind.

**Comment by jtrujill** [comment]
I want to get something out the door and don't want to get stuck in hypotheticals. I'll get a datepicker out that allows a user to pick a date. I'll keep in mind that in the future I'll probably want to extend that for a daterangepicker. For the timepicker I don't see the benefit in having another permutation of datepicker. It would be easiest to keep that as a separate component, especially since must people don't care about that granularity 

Once i have the datepicker out  you can use two datepickers for a  range very easily. The second datepicker can be disabled until a value is chosen for the first. Once the first date has been picked you can set the second datepicker minDate to the first date.

This library is not intended to serve all edge cases. Instead it should give you the tools to complete what you need. I don't want to maintain a complex library that tries to reach everyone's needs.

**Comment by andrew-frueh** [comment]
Not sure I agree that most people don't care about time.  Operations Console is all about scheduling jobs - so that needs a date and time; Care Management schedules patients for appointments, so that needs a date and time, etc.

I think what you've suggested is a good place to start @jtrujill so I wouldn't change your approach to get the component going.  But the point of this thread was to hear how different apps are using datePickers so we could understand the needs better.  So I don't want to be dismissive of the suggestions here.  We don't have to implement them all, but we want this to be a place where everyone can contribute.

**Comment by benjanderson** [comment]
Resolved with #677
