### ISSUE TITLE
Cashmere VS Code Snippets

### ISSUE THREAD

**Issue by jonest** [HealthCatalyst/Fabric.Cashmere#462]
**Describe the problem this feature request is solving**
I've created some snippets to use in VS Code so I don't have to look up the components in the docs all the time and thought it would be cool to publish these as a VS Code extension for users to install! 😄 

**Describe the solution you'd like**
I've got an initial take on the extension and can open a pull request for some feedback while I (or anyone else that's interested) sort through the details of publishing it to the marketplace.

**Comment by jtrujill** [comment]
I don't understand what this is meant to achieve can you explain

**Comment by andrew-frueh** [comment]
Very cool, @jonest!  This wasn't even something we had thought about, so really appreciate you looking for solutions to improving your own experience of working with Cashmere.

Because this is something totally new, before we approve this PR, I'd like to make sure we've thought  through all the angles on this.  So I'd like to hear from all the folks on the steering committee: @benjanderson @jacquie @corykon @jtrujill with any questions or concerns they have about publishing a VS Code extension.

My one concern is that the content included in the extension would become stale or out of sync with the library.  We've just gotten over the hurdle of making sure our documentation on cashmere.healthcatalyst.net is automatically synced up with the library.  So I'd hate to find us in a situation with the VS Code extension where we have to worry about manually curating content again.  Is there any way it can pull its content dynamically or we don't have to worry about parity with the current build?

**Comment by jtrujill** [comment]
I have to second what Andrew is saying. A big refactor was done to the documentation so that our demos and API would never be stale.

**Comment by jonest** [comment]
> My one concern is that the content included in the extension would become stale or out of sync with the library. We've just gotten over the hurdle of making sure our documentation on cashmere.healthcatalyst.net is automatically synced up with the library. So I'd hate to find us in a situation with the VS Code extension where we have to worry about manually curating content again. Is there any way it can pull its content dynamically so we don't have to worry about parity with the current build?

That's something I considered as well and one way that we _could_ generate it is to ignore all the tabbing stuff and just plop in a default block of HTML. We'd essentially just need to generate the `html.json` file with all the lines from the examples.

This could also be something separate that has a dependency on a particular example.

I mostly created this for personal use, but once I'd finished I thought I'd throw this up here to see what people thought. I'd be fine with it just being something totally separate that's in my own personal repo that I (and anyone else interested) maintain.

**Comment by jonest** [comment]
> I don't understand what this is meant to achieve can you explain

@jtrujill Check the #cashmere channel on Slack for an example video
