### ISSUE TITLE
GitHub Issue Labels Change

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#465]
In order to better help with our version releases, I'd like to propose changing the labels that we currently have for our issues.  It's a much shorter list, but it seems like most everything we have on our current issue page would fit into one of these, and the other labels aren't giving us much value:

- **Breaking Change**
- **Enhancement**
- **Bug**

@jtrujill suggested that these tags could be used for our semantic versioning in releases as well.  A release with one or more breaking changes increments the major version, and release with one or more enhancements updates the minor version, and bugs update the patch.  Breaking change trumps the other two, etc.

That feels like a very logical system and takes the guesswork out of our release versioning.  It does remove the "Discussion" label for issues which we've used some - but it feels like most of those issues just went stale and lingered on the board without resolution.  Probably better the items that are strictly discussions without being an update to the library do better on the Slack channel.

Ironically this issue I'm creating is strictly a discussion - but it's the last one, I promise :-)

Let me know what you all think.

**Comment by jonest** [comment]
If it's possible to configure the build to increment the versions based upon the tags I think that's a great idea!

**Comment by jtrujill** [comment]
Could you list the tags you want to have? I could see us needing

- breaking change
- enhancement
- bug
- question
- wontfix
- help wanted
- duplicate

We might also want to look into indicating whether a PR is ready for merging. We should avoid giving everyone write access since they can easily break things unintentionally. We have a standard commit message format that we need to follow, but GitHub gives you the ability to circumvent the commit verification.

**Comment by andrew-frueh** [comment]
Changes have been made to the label categories and all current issues have been updated
