### ISSUE TITLE
Demo fails to load in Internet Explorer 11

### ISSUE THREAD

**Issue by benjanderson** [HealthCatalyst/Fabric.Cashmere#491]
**Describe the bug**
IE11 fails to load https://cashmere.healthcatalyst.net/

**To Reproduce**
1.  Open IE11 
2.  Goto https://cashmere.healthcatalyst.net/

**Browser:**
Internet Explorer 11

**Additional context**
When trying to access https://cashmere.healthcatalyst.net/ through IE11 it fails to load. Opening the dev console reveals the error "Syntax error vendor.js (134317, 27)". Navigating to the code shows the following line
```
const ucs2encode = array => String.fromCodePoint(...array);
```
This piece of code is tied to punycode.js https://github.com/bestiejs/punycode.js/ and it appears this is a current issue with angular

https://github.com/angular/angular-cli/issues/9508#issuecomment-381104612

**Comment by jtrujill** [comment]
So this is a transpilation with the spread operator or maybe the lambda. It looks like punycode@1.4.1 is the breaking change. if you look at 1.4 its written in es5.
 
https://github.com/bestiejs/punycode.js/blob/v1.4.0/punycode.js

Man i hate transitive dependencies like this. Basically it's because @schematics/update updated to a version of npm-registry-client that eventually pulls in a breaking change from punycode. 

`punycode@1.4.1 <= tough-cookie <= request <= npm-registry-client <= @schematics/update <= @angular/cli`

Probably has to do with this [commit](https://github.com/angular/angular-cli/commit/b8b36ba339534732cb951ea08446087b2fae25a3#diff-7e1c497c592bb1293cc4ac62ed7caaa4)
