### ISSUE TITLE
Popover placement incorrect when page is scrolled down

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#567]
**Describe the bug**
If a popover is configured for an element that is at the bottom of the page (i.e. after scrolling down), the popover is not placed correctly.

**To Reproduce**
Reproduce it on stackblitz fork
https://stackblitz.com/edit/cashmere-demo-pdw6cd?file=app%2Fhome%2Fhome.component.html
_AND_

1.  Click on the vertical ellipsis for the first item.  It works as expected.
2.  Scroll down to the bottom.
3.  Click on the vertical ellipsis for the last item.  It seems like nothing happened.
4. Scroll to the top.  You will see the popover for the last item.

**Expected behavior**
Popover should appear next to the thing that is clicked on.

**Screenshots**
![image](https://user-images.githubusercontent.com/12286274/47521188-9b0aea80-d84f-11e8-8fb0-fe7f75f12f3e.png)

**Browser:**

*   All

**Additional context**
I know that we are thinking of moving away from `popper.js` and using Angular CDK for overlays.  This change could fix this issue.

**Comment by benjanderson** [comment]
Good find! I would love to replace the popover with the sdk :)

**Comment by joeskeen** [comment]
Unfortunately, it seems that the split button with its current implementation has the same issue... I tried using it in this StackBlitz: https://stackblitz.com/edit/cashmere-demo-pdw6cd but if you scroll down and click on the button that opens the menu, you end up with a mispositioned (offscreen) menu, **and** it also blocks scrolling on the page until you click the backdrop to dismiss it.  Yuck!

We will definitely need to tackle this issue for both popover and split button...

**Comment by corykon** [comment]
@joeskeen @andrew-frueh @benjanderson I think I've got a fix for the issue with menu positioning in the split button, but haven't touched the popover component. If we were to do a swap as suggested and use the cdk instead of popper.js, it would most certainly be a breaking change. I'm thinking a better approach might be to depreciate the popover component entirely, create a quick "menu" component and suggest people use that, and than go back and make a better generic popover component a little later on. Thoughts?

**Comment by joeskeen** [comment]
I think this might have fallen through the cracks - although we do want to deprecate the popper, an issue was never created to separate out the menu functionality from SplitButton :(

**Comment by corykon** [comment]
There's a brand new popover #783
