### ISSUE TITLE
Tile too wide so you can't see the shadows

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#590]
In the example for the Tile component you can only see the bottom shadow
**To Reproduce**

1.  Go to the example for the Tile component
2.  Observe that you can only see the bottom shadow

**Expected behavior**
You should be able to see shadow on the sides of the tile too

**Screenshots**

**Browser:**

*   Chrome
*   Version [e.g. 22]

**Additional context**
I think it's because the width in the mixin in _tile.scss is set to 100%

**Comment by andrew-frueh** [comment]
Good eye @jacquie - I must confess I never noticed this until you pointed it out.  Coming up with a solution is a little trickier, because we want the tile to extend to the width of its container.  We don't want to add padding because that will throw off it's alignment with other items around it.  Getting rid of the drop shadow and going with an outline would certainly solve the problem, but that would be pretty different.  I'll have to think more about this one.

**Comment by andrew-frueh** [comment]
As we discovered in the steering committee meeting today, the issue here actually isn't with the Tile component but with the Tab component.  The `overflow: auto;` style on `.hc-tab-content-horizontal` is what's causing the shadow to be clipped.  Seems like having overflow on for the content of tabs is probably what we want though, right?
