### ISSUE TITLE
"Load more" pagination

### ISSUE THREAD

**Issue by corykon** [HealthCatalyst/Fabric.Cashmere#599]
**Describe the problem this feature request is solving**
This is a common pagination approach in pop builder:
![image](https://user-images.githubusercontent.com/12416432/48164722-8ba08e00-e2a0-11e8-968a-bac6da3800dc.png)

**Describe the solution you'd like**
A new component that is just a simple "load more" button with the built in functionality for pulling another page of data from table-data-source.ts

**Describe alternatives you've considered**
None

**If any, which components will have to change, and how**
I'll create a new abstract pagination class which the current `hc-pagination` and the new `hc-load-more-pagination` can extend.

In the screenshot above, you'll notice we use a smaller button. I'll just implement using the standard button size. Maybe somewhere down the road we had button size to our button component... sm, reg, lg... not sure it's that important though.

**Comment by andrew-frueh** [comment]
Great description @corykon; and having alternatives for pagination is definitely something that we've heard from multiple app teams.  Two thoughts:

- I like the idea of the abstract pagination class.  Even though this will be a new component, will it still be part of the pagination module?  Feels like that would be the best thing from an organizational perspective.  So on the Cashmere site, these would both live under that "Pagination" tab, but there would be an additional example to illustrate the "load more" style of pagination.  Is that approach what you were planning on?
- What about using a "secondary" `buttonStyle` for "Show More" instead of primary alt.  I think that would make it feel less heavy and you might not have to worry about reducing the height.  If we want to use Google as an example, their show more looks pretty similar to our secondary style - and their button is 27px height, which is less than our 35px, but not too much.  Also note that they center the button and give it a wide 500px width.

<img width="974" alt="screen shot 2018-11-07 at 3 42 11 pm" src="https://user-images.githubusercontent.com/22795893/48165799-fa331b00-e2a3-11e8-89c6-2e6f95d4df9a.png">

**Comment by corykon** [comment]
Yeah @andrew-frueh, I did exactly as you described in your first bullet point :+1: 

As for the styling - my PR has primary-alt as the default. Would you like me to change that to secondary, center it horizontally, then maybe set the min-width to like 30%?

**Comment by corykon** [comment]
@andrew-frueh would look something like this:
![image](https://user-images.githubusercontent.com/12416432/48166266-4df23400-e2a5-11e8-82f0-f47921cb0848.png)

**Comment by andrew-frueh** [comment]
Cool - I was just testing out something similar to your screenshot in the PR you submitted.  I've been doing some looking around to see if there is a consensus out there in terms of size/position/color of a "Show More" button.  It does feel like centering is the more common practice - so that's great.

For the size I do like it bigger as you have it.  Do we need to consider the size when it's on mobile screens?  I guess that could just be contained in a breakpoint.

As far as the color, I'm 50/50 on whether I like `hc-secondary` or `hc-neutral` for the style.  I like either of those because I feel like they won't compete with the real primary buttons that an app might have on their page.  I'm leaning towards `hc-neutral` because it's a little stronger but still doesn't compete.  What do you think @corykon?

**Comment by andrew-frueh** [comment]
Oh one other minor comment/suggestion.  For the example, would it make sense to include pageSize as an input as well.  I had to flip to the html to see how that was being defined - which is fine, but showing it as an input might make that clearer.  And out of curiosity, shouldn't the "Current Page Number" increment every time I hit the load more button?  I see the indices displayed increase, but not the page number (I'm using Firefox).
