### ISSUE TITLE
Picklist

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#61]
Much credit to @corykon and the Population Builder team for developing a pattern that has been followed by a number of apps.  The picklist is called upon when a user needs to select a number of items from a potentially length list of options.  Although the picklist component would most commonly be used within a #40 modal dialog, it can stand alone as well.  Cory, I know I've already dropped the massive "table" component on your plate, but since you set the standard here, I think you'd be the most qualified to componentize this.

![picklist](https://user-images.githubusercontent.com/22795893/35548996-5a17da0c-0540-11e8-8255-62624a7f2575.png)

**Comment by jtrujill** [comment]
This is similar to a the list component that I've created. I'm going to be expanding it's capabilities further so that it can have a header and divider between items. 

I'm thinking for this component that it'd be best to provide developers with the tools to accomplish 80% of this and have them implement the rest. There are just so many ways that this could be different between applications, that it'd be very difficult to provide them a component that would be useful for their particular needs.

I think the most difficult part about this is creating a selectable list, which is something I plan to write. It will build off of the list component and will provide an easy to use interface that would allow you to do all of the above. Once the selectable list is implemented the implementation of this design would be very easy.

If you can just assign this to me, I can look at extending the list component

**Comment by corykon** [comment]
Sounds good, Jeremy. For reference, here's where you can play with what we've got in builder:
- [https://hcs-clinicalppr.hqcatalyst.local/test/ruleset/new](https://hcs-clinicalppr.hqcatalyst.local/test/ruleset/new)
- New Ruleset > Drag out a Diagnosis Fitler > open "Diagnosis Codes" from drawer

Would be good to make note of the functionality that is there- not that you'd implement it all, but would be cool if you could try to match the feel of the picklist that's there, and architect things such we'd be able to build on top of the cashmere component and achieve the functionality that's there.

**Comment by andrew-frueh** [comment]
One bit of commentary, @jtrujill - I agree that this type of picker _could_ be very custom from app to app, but we do in fact have three or four Catalyst apps that use it exactly as @corykon has it built out in PopBuilder.  I'm all for customization, but my request would be that the PopBuilder style be the default so the multiple apps using the same functionality can plug and play.

**Comment by jtrujill** [comment]
Maybe in addition to the selection list I can look at making a component which allows you to transfer objects from one list to the other. I don't think that would be too difficult and would reduce the amount of work required of a user to implement the design.

**Comment by jtrujill** [comment]
Maybe not a component but a directive
