### ISSUE TITLE
ViewEnapsulation

### ISSUE THREAD

**Issue by jtrujill** [HealthCatalyst/Fabric.Cashmere#74]
The below is from a PR #71 

> There is no issue with turning view encapsulation off for a library component and the reason is that when the user of a library uses a component within their own component which should have ViewEncapsulation.Emulated any changes that they make to the component will not leak out of that component.
> 
> What we are doing by having the color property is giving the user access to preset css values that match our company's design doc, but there will be situations where the user will need to change the component slightly.

We should not have viewEncapsulation enabled on our components for the reason ^. If we take the button example above which has a color property that sets the color of the component and I believe this is a good use case for !important to prevent other css from changing that. There will be times when our components styles will need to be changed. How often have you as a developer needed to change your own component's styling for 1 or two pages? 

This will happen so I suggest that we turn viewEncapsulation off to enable users to make those changes. What we should do with this library is give the users great presets that match the company's style guide.

Thoughts?

**Comment by corytak** [comment]
I'm torn on this one. While Cashmere is technically an open source angular component library, it is also our company's living style guide. Its use will be mostly internal to Health Catalyst so it seems less likely that there should be a need to override the styles. All of the buttons in our apps should be the same size and the same colors. If any apps are using Bootstrap/Foundation/Material, those styles have the potential to collide with the Cashmere components in unexpected ways.  

I agree that inevitably there will come a scenario where I'll want to tweak a property, but I almost want to leave viewEncapsulation enabled on our components so that those issues are surfaced to us as issues. It may be that something is a one-off tweak for only one team, but it may also be the case that this one-off tweak is actually something that needs to be considered as an additional feature for one of our components so we don't have several teams making the same one-off tweak. 

Here are some lists I've started about pros/cons of each

View Encapsulation Enabled:
- Components look and feel the same regardless of context (pro)
- More difficult for teams to stray from style guide (pro (& con?))
- Potentially lower cashmere adoption rate (con)
- Instead of teams tweaking existing components, they get re-routed as issues/features to cashmere (pro)
- Components may get riddled with too many inputs/complicated interfaces (con)

View Encapsulation Disabled:
- Components have style guide defaults and it's easy to follow HC style guide (pro)
- Easier to stray from style guide (pro (& con?)
- Higher cashmere adoption rate (pro) ("I  would use cashmere but it doesn't work for this particular scenario")
- Rework (many teams completing same tweaks to components) (con)
- Component interfaces remain simple (pro)

I would love to get others thoughts on this too.

**Comment by jtrujill** [comment]
I get what you're saying there could be issues if for example someone has unscoped css, and what I mean by this is they don't have the styles wrapped in a class. For example I've seen this kind of scss

```css
table {
  tbody {
    tr {
      td {
        width: 30px;
        color: red;
      }
    }
  }
} 
```

There are multiple things wrong with the above first it makes that td element so specific that it's ridiculous to try and override the styling. The other issue, which is only an issue if you turn encapsulation off, is that you have an unscoped table element. What you should do is either give that table a css class or put it under the component's css class:

```html
.hc-table {
  td {
    width: 30px;
    color: red;
  }
}
```

or

```html
.hc-table-data {
  width: 30px;
  color: red;
}
```

This would require that people scope their css class names to the hc namespace. Now, for components that don't follow that, we could leave them with encapsulation until we're able to make the necessary changes.

**Comment by jtrujill** [comment]
**View Encapsulation Enabled**

> More difficult for teams to stray from style guide (pro (& con?))
I actually think it's more likely to cause team-members to stray from using the library if they can't style the component how they need, which is a larger issue
> Potentially lower cashmere adoption rate (con)
^^
> Instead of teams tweaking existing components, they get re-routed as issues/features to cashmere (pro)
I believe this is related very much to the con you have listed below
> Components may get riddled with too many inputs/complicated interfaces (con)
If we try to make this an all-purpose library, it is likely to get bloated in both styling and function and will be incredibly difficult to maintain. We can't try to cover every edge case that will ever pop up so I totally agree with this con, and that's why I'm so bent on using no encapsulation

**View Encapsulation Disabled** 
> Easier to stray from style guide (pro (& con?)
I don't think this will be an issue. I believe that most of the time the defaults will be used.
> Rework (many teams completing same tweaks to components) (con)
There's this possibility, but if the person submitted an issue we as a team could decide if it's worth implementing in the component for everyone

As long as we properly scope our stuff and make sure it's not too nested, which follows css best practice, we will have a very robust library that other developers within the company will use. I know that if we structure these components too rigid, I and many others, will look to our own components, just so we can style it correctly.

**Comment by corytak** [comment]
Good points. Maybe it doesn't have to be an all or nothing thing and we can decide on a component by component basis? I agree completely about namespacing our css to avoid conflicts (I believe there are even some scenarios with view encapsulation enabled where conflicts can occur) and you've changed me from a staunch believer in "view encapsulation enabled only" to someone who thinks it makes sense at times to disable view encapsulation with other checks in place, especially in the development of a reusable library.

**Comment by waldnercharles** [comment]
Are there any popular libraries which allow users to customize the style of their components? If so, how are they handling it?

Having inputs for each css property we want users to customize seems like it would quickly become cumbersome. Alternative themes seems like a good idea, but doesn't necessarily solve the issue.

Though, If we want to allow custom-styling for our components, setting view-encapsulation to none seems like a sane solution.

**Comment by isaaclyman** [comment]
My experience with popular libraries (in and out of Angular) is that they don't consider the needs of users who stray from the presets. Said users usually are not motivated by artistic aspirations or a desire to stray from approved styles, but by design specs that require functionality above and beyond what the library offers.

There's an exponential relationship between how complex/large a component is and how often users' needs will not be met by it. For example, a "button" component can meet almost everyone's needs without much customization, assuming it has 10 or 15 official variants - ok button, cancel button, warning button, danger button, 'split pill' button, button with a custom dropdown, button attached to an input, button with an icon, and so forth. Whereas a "modal" component will require unforeseen customization in a significant percentage of cases, since the content, workflow, and environment of any given modal is highly volatile.

A library has never offered me a friendly way to restyle a component or substitute out some of its functionality. I've always had to use high-specificity CSS selectors or the !important hammer for styling, and really hairy JavaScript or ditching the component altogether for functionality.

If we want to encourage adoption, we should be helpful but not prescriptive about component styling and functionality. This means:

- The flattest CSS we can possibly manage (specificity of 1 in most cases)
- Well-named classes, preferably with a library-specific prefix (like `hc-`)
- No view encapsulation

Nobody restyles a component by accident--they do so intentionally, and in my opinion making it more difficult just makes it more difficult.

**Comment by jtrujill** [comment]
Disabling ViewEncapsulation is the way to go. We'll need to create a ticket to fix the components that don't have that disabled
