### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by andrew-frueh** [HealthCatalyst/Fabric.Cashmere#79]
Translate @corykon's incredible work on [table styling](https://github.com/HealthCatalyst/Fabric.Cashmere/pull/73) into a full Cashmere component.

- [x] Sorting (client side)
- [x] Paging (Client side) (toggle between more results button & numbered pagination)
- [ ] Toggle to choose page size
- [ ] Bake in checkboxes (input row type extend some `IsCheckable` class that has an `isChecked` property?)
- [ ] Input Table Options (total number of pages (server side pagination) rows per page, server/client side pagination, checkboxes/selectable rows)
- [ ] Table Output events (current page, selected rows, sortEvents for server side pagination)
- [ ] Documentation
- [ ] Tests

**Comment by jtrujill** [comment]
I'm going to make the suggestion that we use https://material.angular.io/cdk/table/overview. We could write a wrapper components around these and provide our own stylings that @corykon had written. The CDK is a component developer kit written by Google which provides many useful features that we could make use of such as portals and layout.

**Comment by corytak** [comment]
Wanted to throw in some lessons learned from our homegrown table component. We built a table component that was all in one large component rather than a suite of components/directives. This became unwieldy because the table component required inputs of

- rows that were typed as `TableRow`
- headers that were typed as `TableHeader`

This forces the consumer of the table to map arrays of other objects to be conformed to those specific types. 

It's also run into limitations when trying to include custom content in the table rows. If we start from scratch, I would advocate for creating a symphony of directives and components rather than squishing it all together inside one component.

**Comment by petermcclanahan** [comment]
Here are some thoughts about grids in Atlas and our use of material

1. We wanted to create separate components for pagination, page size, sorting, and filtering. MetadataService has an odata back-end and we want to pass values from those components into the MDS calls. That said, using material didn't give us the pagination, or sorting, any of those things as we thought it might have originally. 

2. We found the whole `DataSource` thing pretty confusing, and not necessarily intuitive. It's made getting the data into the grid kind of awkward in our `base-grid.component`

3. I can't remember all the reasons now, but we were interested in using transclusion with our grid for some reason. We tried for a while trying to get it to work with the material table, and eventually had to look into other options. 

4. There have been some interesting bugs that are hard to track down when the number of columns in the `DataSource` don't match the number of columns in the markup, or when the names are different.

In the end, I think if we had to do it over, since material isn't giving us very much, we'd seriously consider just writing it ourselves, and not being tied to material.

**Comment by jacquie** [comment]
I thought we'd agreed that using third party libraries was generally not a good idea? Tables are used in so many ways and degrees of sophistication that it seems to me it would be impossible to create something everyone will be happy with - an all singing, all dancing component would be overkill for something that really just needs a straight up table and, as we've seen, never quite meets all the needs for every situation. I like all that Cory's idea of a 'symphony of components' implies - components that play together, and that you can pick and mix from to suit your particular table needs.

**Comment by jtrujill** [comment]
The difference between those libraries and the cdk is that those libraries introduce global variables which always interfere with each other. I also think this would go far to cover a lot of base cases. Again we shouldn't aim to please all cases

**Comment by jacquie** [comment]
Well I would feel bad for the cases we can't please :( I am confident that between us we could come up with  something innovative and modular that caters for most things and leaves the door open for expansion/enhancement as and when needed.

**Comment by andrew-frueh** [comment]
As was brought up in our meeting today, it would be great if Cashmere can make the spin-up time for new apps much smaller.  And given that tables are something every app uses, if a new dev team was able to just grab a table component off the shelf, pump some data in, and be ready to go - that would be ideal.  But I like the way @jacquie said it, we'd just need to make sure that component "leaves the door open for expansion/enhancement".  So if CDK is the way to make that a reality, than that sounds good to me (knowing that anyone who wants to write something _super_ custom can always fall back on @corykon's css).
