### ISSUE TITLE
Release pipeline and Semantic Versioning

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Cashmere#83]
After our open space session, I wanted to post here and start a discussion around the process of publishing to npm with a prerelease tag. Main questions include:

- Should the CI pipeline automate the version and publish when committed to master
- Should we submit pull requests to a dev branch and update the version when we migrate the dev branch to master?
- Should the user submitting a pull request to master set the version in `package.json`?

What have you all seen in the past? What would be the preference?

**Comment by jtrujill** [comment]
My thought process is that we should setup some kind of staging branch(dev) that we merge into. When it's time to cut a release we could have someone in charge of updating the app version and merge that into master.

Then we could have a Travis task which watches for changes to master only and will deploy on success of the other tasks

**Comment by jtrujill** [comment]
@corytak @benjanderson This would work amazingly for what we need https://github.com/semantic-release/semantic-release. We can use this for automatically incrementing the app version and for publishing to NPM. 

This works by using a commit messaging standard in order to parse the change-log. This would require that people squash their commits, which is a good idea to do anyways. It doesn't help any to have a bunch of commits from a feature branch merged into master, especially when those commits can lead to a broken app state.

https://github.com/commitizen/cz-cli can be used to help write commit messages which fit the commit message standard.

**Comment by jtrujill** [comment]
An alternative to squashing is making an initial commit using `git commit --amend` for subsequent commits

**Comment by jtrujill** [comment]
Forgot to mention it also helps to create change logs which will be important to have

**Comment by jtrujill** [comment]
@corytak @corykon @joeskeen @benjanderson @andrew-frueh 

To go along with that there is a tool that can verify all commits called commitlint https://github.com/marionebl/commitlint

On that page are instructions for setting this up locally and on the CI server. This will help to ensure that all commits match the commit style that we choose.

With commitlint and commitizen using semantic-release will be easy to implement with a large team, especially since commitizen will generate an appropriate message for you.

As I've said above, each commit will be required to follow this standard, so it'll require that people amend their commits, squash or provide a useful message for every commit they make for a PR.

However, a PR should only focus on one thing.

**Comment by corytak** [comment]
I love the idea of changing the version to 1.0.0 with an alpha tag rather than incrementing the patch release.
