### ISSUE TITLE
Time Picker for Date Picker

### ISSUE THREAD

**Issue by joeskeen** [HealthCatalyst/Fabric.Cashmere#946]
**Describe your idea**

Similar to the Date Range picker, we could create a Date Time picker that has both calendar and clock.

**What problem are you trying to solve?**

We currently have a few use cases where we need to capture both date and time, not just date.  Currently the Date Picker component does not support time.

**Comment by andrew-frueh** [comment]
As I was working on updates to the DatePicker UX - I came across a few date pickers that combine date and time into one dropdown.  Below is a typical example of how that usually works:

![1*5X3hg1EW7wbi4DwJBor9og](https://user-images.githubusercontent.com/22795893/65625401-0215af80-df89-11e9-9fa5-4ac4b48cff89.png)

**Comment by corykon** [comment]
@andrew-frueh How do you feel about this tweak on the date/time picker?

![image](https://user-images.githubusercontent.com/12416432/70841473-f68f9300-1dd7-11ea-9f0d-c40eb62447a4.png)

The design on the right saves a bit of vertical space, and gets rid of that issue where the "jump to today" link looks like a header for the time control, but, "today" is a bit less clear than "jump to today".

**Comment by andrew-frueh** [comment]
I think that's a good suggestion @corykon.  @joeskeen made that suggestion (to change it to "Today") a few revisions again and I passed on it because it made the button too small when it was the only thing down at the bottom.

Do me a favor and run this by Alejo, since he's done some testing on the datepicker and has a good sense of how his users interact with it.  If he's good with the change, then go ahead and get a PR submitted.  And the timing is good too, because I was planning on building a test on usertesting this week to validate the UX of the new time picker.  So if we can get this change in, we can test out how users do with it too.
