### ISSUE TITLE
Progress Indicators

### ISSUE THREAD

**Issue by jacquie** [HealthCatalyst/Fabric.Cashmere#96]
What kinds do we need and what should they look like?

**Comment by andrew-frueh** [comment]
Great suggestion @jacquie - I wonder if we could get this issue started by having folks post screenshots for the process indicators they are currently using.  We put a suggestion in the style guide, but we never really proved it out, so I know there are a number of approaches floating around out there.

**Comment by jacquie** [comment]
On Leadingwisely  we've been using the material one, but it doesn't always cycle very neatly. and where we have a million charts, cards loading at once they look somewhat large and cumbersome.  We added an Observable based service to it signal when it should hide or show - I don't know if we could/should incorporate that into a shared component or if it should be left to the user to decide how to achieve that part. [https://material.angular.io/components/progress-spinner/overview](url)

**Comment by jtrujill** [comment]
On cafe we had our own infinite spinner
<img width="220" alt="screen shot 2018-02-05 at 1 41 29 pm" src="https://user-images.githubusercontent.com/5596515/35827727-5db6c85a-0a7a-11e8-9fcf-b53f7da6c91a.png">

If this is alright I can modify it and get it uploaded

**Comment by andrew-frueh** [comment]
I'm realizing the solution @jacquie's suggestion for progress indicators is probably multifaceted.  As we've all discovered there usually isn't a one size fits all progress indicator because there are many different situations where they are needed - at a full page level, at an individual element level, and initial app loading too.

At least for initial app loading, what @corykon came up with on Population Builder has set the standard that Measures Manager, Leading Wisely, and maybe others as well are using:

![popbuilderloader](https://user-images.githubusercontent.com/22795893/36055137-7d430fcc-0db7-11e8-8fb7-f69a041c738f.png)

As Cory pointed out, something like this would display before Angular loads - so it wouldn't be a component per se.  But if we could create sharable markup and css in Cashmere, that would be a good place to start.  @corykon, @corytak, @jacquie or anyone else who is making use of that initial loading screen interested in incorporating it into the library?

**Comment by jacquie** [comment]
Ours has the triflame and the leadingWisely flexo svg in it - not sure if we want that though if there is going to be app switching?

**Comment by andrew-frueh** [comment]
I thought I remembered that @jacquie.  As per usual, I suspect each app is doing this loader slightly differently, so that's a great reason to pull it into the library so we have one version we all agree on.  If you or @ckeates want to put your version into the library to get us started, we can tweak the styling together from there.

**Comment by andrew-frueh** [comment]
@corykon - could I perhaps assign this one to you?  We had talked about some ideas you had for spicing up our loading spinner, which I think could then be applied to a spinner that could be used elsewhere.  And maybe you could also include the inline progress indicator you're using on Pop Builder when loading values (the three dots)?

**Comment by corykon** [comment]
#167
